dsp:
  windowed_frames:
    window_type: hann
    window_size: 256
    padding_factor: 0
    zero_phase: true
    sqrt_window: false
    return_padded_signal: false

  stft_features:
    sample_rate: 8000
    hop_size: null
    features: 
      - magnitude
      - phase_norm